<?php
/**
 * @file
 * A block module that displays links to private messages tagged "feedback requests" (requests to provide feedback on recently downloaded files).
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function feedback_block_help($path, $arg) {
  switch ($path) {
    case "admin/help#current_posts":
      return '<p>' . t("Displays links to private messages tagged 'feedback block'") . '</p>';
      break;
  }
} 

/**
 * Implements hook_block_info().
 */
function feedback_block_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Feedback requests'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Custom content function. 
 * 
 * Load messages as subject headers linked to message view. 
 * 
 * @return 
 *   A result set of the targeted posts.
 */
function current_posts_contents(){

	global $user;

	// Generate the query to load the messages.
	// Replace 'inbox' with 'sent' to display sent messages or 'list' to display all messages.
	$query = _privatemsg_assemble_query('list', $user, 'inbox');

	// Load 5 messages/threads. Replace 5 if you want to display a different amount of messages.

	$list = array();
	$count=0;
	foreach ($query->execute() as $thread) {
	  if ($count <=5) {
	    // Generate a link with the subject as title that points to the view message page.
	    // $list[] = l($thread->subject, 'messages/view/'. $thread->thread_id);
	    // take a look at $thread to see if what you needed is already there, so you can bypass other theming functions (you probably shouldnt)

	    // proper solution:
	    $theme_variables=array('thread' => (array)$thread);
	    $subject=theme('privatemsg_list_field__subject', $theme_variables);
	    $list_parts[]=$subject['data'];
	    $list_parts[]=t('from');
	    $participants=theme('privatemsg_list_field__participants', $theme_variables);
	    $list_parts[]=$participants['data'];
	    $last_updated=theme('privatemsg_list_field__last_updated', $theme_variables);
	    $list_parts[]=$last_updated['data'];
	    $list[] = implode(' ',$list_parts);
	    $count++;
	  } else {
	    break;
	  }
	}

	// Display list as a themed item_list.

	print theme('item_list', array('items'=>$list));
}
